# Generated by Django 3.1.5 on 2021-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='request_token',
            new_name='refresh_token',
        ),
    ]
